name: CI
on:
  workflow_dispatch:
    inputs:
      publishSnapshot:
        description: "Publish Snapshot"
        required: false
        default: false
        type: boolean
      publishMicrosite:
        description: "Publish Microsite"
        required: false
        default: false
        type: boolean
  push:
    branches: ["scheduled-job"]
  schedule:
    - cron: '* * 17-18 7 *'


jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'schedule' || github.event.inputs.publishSnapshot
    steps:
      - echo "Releasing now!"
